### ISSUE TITLE
className option does not seem to be working

### ISSUE THREAD

**Issue by rgriffith** [DataTables/Select#10]
I am providing the [`className` option](https://datatables.net/reference/option/select.className) when initializing my Data Table and it does not seem to be used. Instead, I am just getting the default `selected` class:

```
$table.DataTable({
  select: {
    className: 'info',
    info: true,
    style: 'single'
  }
});
```

Also, is it just me or does the example on [this page](https://datatables.net/reference/option/select.className) look incorrect with the nested `select` options?

**Comment by DataTables** [comment]
It appears to work okay [with this little example](http://live.datatables.net/ralevose/1/edit). You need to use the inspector to see the class being added - but it does use the correct class.

Can you link to a page showing the issue please? Also worth noting that you need to be using Select 1.1.0 for this to work (there was no 1.0.2 that the doc references - also fixed :-) ).

**Comment by rgriffith** [comment]
Ah I was running 1.0.1, so that was the issue. Again, thank you for the help. Closing this out.
