### ISSUE TITLE
bootstrap css hardcodes default colors

### ISSUE THREAD

**Issue by sirianni** [DataTables/Select#12]
It would be great if the datatables.select bootstrap styling could accommodate bootstrap themes/variables.  This would likely require providing a SASS version of the styles that used bootstrap-defined variables like `$brand-primary` instead of hardcoding color values.

**Comment by sirianni** [comment]
Actually, it might be even simpler.  Just use the bootstrap class `active` on the `TR` instead of having datatables provide custom CSS.

**Comment by sirianni** [comment]
Perhaps this issue should be move

**Comment by sirianni** [comment]
Perhaps this issue should be moved to the datatables-select-bs project

**Comment by DataTables** [comment]
Its not quite as simple has having only the `active` class (depending upon your configuration) as DataTables can highlight the sorting column (i.e. the cells in the column) which needs to be taken account of as well.

Using the Bootstrap variable as a default is probably the best option.

Filing the issue here is the correct place to locate it - the datatables-select-bs repo is just a distribution repo that is built from this one.

**Comment by julienlegault** [comment]
Is there any decision as to what bootstrap color it should default to? `$primary` seems like an obvious one, but I also really like `$brand-primary`. `$info` seems to be the bootstrap default that looks closest to current highlight color. [Bootstrap 5.0](https://getbootstrap.com/docs/5.0/customize/color/) has a lot of other color options so `$blue-100` or `$cyan-200` are both possible options as well.

**Comment by DataTables** [comment]
We never did progress this very far. I guess we have two options:

1. We can use Bootstrap's SCSS variables, but that would then require you to compile our SCSS files, which we don't distribute on the CDN or the packages, or
2. Use CSS variables, which is probably my preferred option, but we'll need to think about how we can retain backward compatibility with legacy browsers that don't support them and how to specify defaults should the Bootstrap CSS not have the variable defined for whatever reason.

**Comment by AllanJard** [comment]
CSS variables is how I did do this in the end. Use `--dt-row-selected` to control the row selection colour.
