### ISSUE TITLE
Have changes broken the custom selector option?

### ISSUE THREAD

**Issue by jongray** [DataTables/Select#13]
Have changes between 1.0.1 and 1.1.0 stopped the custom selector from working as expected?

I currently have a rows which contain buttons (and occasionally text input or select) - when a user clicks on those elements I don't want the row to be selected. It seems I can enforce that by specifying a selector option of ":not(:input)". This works in version 1.0.1 but not in 1.1.0.

Has the addition of line 266 caused the original logic to now fail?

I can't figure out whether the old behavior was intentional or not, it's certainly the behavior I want in my application.

Test case to follow.  As suggested, I will also try adding the stopPropagation() to the custom button event handler.

**Comment by AllanJard** [comment]
So sorry I never replied to this. The use of `select.selector` appears to be working okay: https://datatables.net/extensions/select/examples/initialisation/checkbox.html , so going to close this.
