### ISSUE TITLE
Support disable checkbox and select

### ISSUE THREAD

**Issue by luqin** [DataTables/Select#16]

**Comment by DataTables** [comment]
Could you provide a description of the issue please. I don't understand what you are looking for from just just the title.

**Comment by scribbly** [comment]
I've come here from a searching for this functionality:

I have a table with selection checkboxes that I've added a .disabled class based on the value in another field. I don't want users selecting the row when the checkbox is disabled.

The cursor displays correctly (i.e. 'no entry'), but the row can still be selected.

Thanks

**Comment by DataTables** [comment]
Select doesn't use real checkboxes though (at least not the default built in ones). Are you using a custom selector or something?

**Comment by scribbly** [comment]
Yes, I added my own render:
`{
  title: "" ,
  render: function(data, type, row,meta){
    var checkbox = $("<input/>",{
            "type": "checkbox"
        });
        if(row[9]>0){
            checkbox.addClass("disabled");
        }
        return checkbox.prop("outerHTML")
    } },`

i.e. if column 9 has a value then I don't want it selectable.

**Comment by DataTables** [comment]
Presumably that doesn't work with the 'row().select()' method? I suspect that checkboxes have more issues that just the disabled attribute as it isn't something that I tried to account for in the code.

**Comment by scribbly** [comment]
Have not tried, to tell the truth... I naturally thought it'd just work out of the box ;)

I'll have to check that method... but the selection works fine, except it selects when disabled.

Otherwise, is there another way I can set a row as unselectable?

**Comment by scribbly** [comment]
How about returning false from user-select()?

Though I'm a bit lost how to get the 9th cell from the cell parameter of the function?

**Comment by DataTables** [comment]
Yes - returning `false` from the `user-select` event is how to make a row unselectable.

**Comment by scribbly** [comment]
Thanks: ( originalEvent.target.className.toLowerCase() === 'disabled' ) does the job!
