### ISSUE TITLE
Additional buttons taking filtering into account

### ISSUE THREAD

**Issue by Stadly** [DataTables/Select#23]
A button for (de)selecting all filtered results would be very useful. Then you could type in a search string to display the rows you are interested in, and the `selectFiltered`-button would select all of these. As you know, the `selectAll`-button selects all rows, without taking the filter into consideration.

If you are interested in all rows except a few, you could use the `selectAll`-button to select all rows, use filtering to show the rows you are not interested in, and then use the `deselectFiltered`-button to deselect these.

Buttons like `selectPage` and `deselectPage` could also be useful, when you don't want to (de)select anything that is currently not visible.

**Comment by DataTables** [comment]
I think a custom button is probably the best way here:

``` js
dt.rows( {selected: true, filter: 'current'} ).delselect()
```

I'll have a think about how it might be included in the API in future, but for the moment a trivial custom button is the way forward. Thanks for the suggestion.
