### ISSUE TITLE
Multiple quick clicks don't trigger 'select' event

### ISSUE THREAD

**Issue by bartekbp** [DataTables/Select#24]
I've noticed that selection event is not generated in case of multiple quick clicks in a single table row. https://datatables.net/extensions/select/examples/api/events.html reproduces this issue.

I was able to find the difference in code flow and it looks like the culprit is [click.dtSelect event handler](https://github.com/DataTables/Select/blob/master/js/dataTables.select.js#L347). `window.getSelection().toString()` in case of omitted clicks, returns string consisting of a single character...

My browser:
Chrome 51.0.2704.103 m (64-bit)
datatables.net-select 1.1.2

**Comment by DataTables** [comment]
It sounds like you are running into the code that is causing the select to not happen if text is selected (I found it really annoying that a row was selected / deselected when you click and drag to select text).

If the browser is saying that a letter has been selected, then that is what is causing this.

**Comment by bartekbp** [comment]
Thank you for the response. 

It looks like current behaviour is correct:)

**Comment by DataTables** [comment]
Closing this issue - I forgot to before when we discussed this.
