### ISSUE TITLE
Style changed to `os` if table has class `selectable`

### ISSUE THREAD

**Issue by simshaun** [DataTables/Select#25]
If the table has a _selectable_ classname but is initialized in JS with the `selectable` option declared, then Select should not change the select style.

The line involved is here: https://github.com/DataTables/Select/blob/cbcf362d573271c1309f8de0af5b6b9398f9b752/js/dataTables.select.js#L132

It's problematic because it prevents people from using the _selectable_ classname for styling purposes while using a style other than `os`.

**Comment by DataTables** [comment]
Thank you! Fix committed and I'll release an updated version soon.
