### ISSUE TITLE
Select doesn't correctly initialize

### ISSUE THREAD

**Issue by ashl1** [DataTables/Select#3]
I have 3 DataTables 1.10.8 (ajax on, server-side off) on the page each with Editor 1.5.0. The latest Select extension. I don't initialize select in any DT options, just include in `<script>`.

In initialization Select produce error in JQuery-2.1.4: 348 - TypeError: Cannot read property length of undefined. It seems that `ctx.aanFeatures.i` is `undefined` in [dataTables.select.js:L340](https://github.com/DataTables/Select/blob/master/js/dataTables.select.js#L340)

The stack trace attached below:

![dt select bug](https://cloud.githubusercontent.com/assets/4058628/9555359/32b6e464-4dd5-11e5-8c69-03b32cd964ae.png)

**Comment by DataTables** [comment]
Can you try this version of Select that is in this repo please. This issue should already be fixed by 2262790bf17afa37d859322d67652179f7d40841.

**Comment by ashl1** [comment]
I see. It works fine in this case.
