### ISSUE TITLE
IE/Edge bug upon select: Object doesn't support property or method getRootNode.

### ISSUE THREAD

**Issue by caitlineatman** [DataTables/Select#31]
The following commit is not supported in IE:
https://github.com/DataTables/Select/commit/0c793f820fdf36cf5fc1a54fa102adb88cd7f2b3#diff-7d61f891a3f3cc950e50716b8600aa54

`getRootNode` is not a supported method in IE. I get an error every time I try to click outside of the table when using IE/Edge. View my forum discussion here: 
https://datatables.net/forums/discussion/42275/ie-edge-bug-object-doesnt-support-property-or-method-getrootnode?new=1

**Comment by lvmajor** [comment]
I don't know why but I still have this error with Select 1.2.2 in edge, I will try to investigate.
Using datatables 1.10.16 with bootstrap 4
