### ISSUE TITLE
After change default wrapper class Select not working

### ISSUE THREAD

**Issue by ds-codemag** [DataTables/Select#33]
When I changed default class "dataDtables_wrapper" to another Select stops working.
In extension code i found that default class is used as selector to "Ignore clicks inside a sub-table"

Code:
`if ( $(e.target).closest('div.dataTables_wrapper')[0] != dt.table().container() ) {
    return;
}`

I simply change this to:

`if ( $(e.target).closest('div.' + $.fn.dataTableExt.oStdClasses.sWrapper)[0] != dt.table().container() ) {
    return;
}`

Now it works for me but I think that you could do this much better.

**Comment by DataTables** [comment]
Because the classes can be changed before each initialisation of a DataTable, each table instance creates a copy of the classes it is assigned, so you can use `dt.settings()[0].oClasses` to get the classes for that instance. The fix I've committed uses that approach.

Thanks for bringing this up!
