### ISSUE TITLE
JQuery Exception when wrapper has 2 spaces in class

### ISSUE THREAD

**Issue by eazrael** [DataTables/Select#37]
This is a little bit weird and I am not sure whose error this is in case it qualifies as such. Running 
- Datatables-Select 1.2.6
- Datatables-1.10.18 (+semanticui)
- JQuery 3.3.1

In the function enableMouseSelection is this piece of code (line 369ff):
```
var wrapperClass = dt.settings()[0].oClasses.sWrapper.replace(/ +/g, '.');

// Ignore clicks inside a sub-table
if ( $(e.target).closest('div.'+wrapperClass)[0] != dt.table().container() ) {
    return;
}
```
This triggers this exception: 
```
jquery-3.3.1.js:1541 Uncaught Error: Syntax error, unrecognized expression: div.ui.grid.dataTables_wrapper.
    at Function.Sizzle.error (jquery-3.3.1.js:1541)
    at Sizzle.tokenize (jquery-3.3.1.js:2193)
    at Sizzle.compile (jquery-3.3.1.js:2587)
    at Sizzle.select (jquery-3.3.1.js:2677)
    at Sizzle (jquery-3.3.1.js:845)
    at Function.Sizzle.matchesSelector (jquery-3.3.1.js:1504)
    at jQuery.fn.init.closest (jquery-3.3.1.js:3060)
    at eval (eval at <anonymous> (dataTables.select.js:372), <anonymous>:1:13)
    at HTMLTableCellElement.<anonymous> (dataTables.select.js:372)
    at HTMLDivElement.dispatch (jquery-3.3.1.js:5183)
```
Some debugging: 
```
> e.target
<input type=​"checkbox" class=​"dt-checkboxes">​
> $(e.target)
jQuery.fn.init [input.dt-checkboxes]
> wrapperClass
"ui.grid.dataTables_wrapper."
> $(e.target).closest('div.'+wrapperClass)
jquery-3.3.1.js:1541 Uncaught Error: Syntax error, unrecognized expression: div.ui.grid.dataTables_wrapper.

```

The issue is the class tag of the closest wrapper found: 
`<div id="data_table_wrapper" class="ui grid dataTables_wrapper<space><space>no-footer">`
The issue seems to be the double space before no-footer.  No idea why Datatables or jQuery generate this code. 

I tried changing the regex to consume double spaces, but this does not work as the string before the regex is missing the no-footer but has a trailing space:
```
> dt.settings()[0].oClasses.sWrapper
"ui grid dataTables_wrapper "
```
For me I fixed this particular case by replacing the wrapperClass assignment line with
`var wrapperClass = dt.settings()[0].oClasses.sWrapper.replace(/ +$/,'').replace(/ +/g, '.');`

but this is hardly a good solution. Any idea what went wrong?

**Comment by DataTables** [comment]
Have you got a link to a page showing the issue so I can debug it please?

**Comment by eazrael** [comment]
Wow, that was fast :-)
https://evilazrael.net/tmp/dtselect/dtselect.html

I am currently converting from a Bootstrap template to a Semantic UI template which used a lot of outdated libraries, so I am also in the process of updating these libs, but this should not impact Datatables.

**Comment by DataTables** [comment]
I only wish I could be this fast all the time...

2b710c73610642c350cc774189fccb0e12823061 should address this. Its not really the best solution, but the whole thing there is a bit of a workaround as it is...

**Comment by eazrael** [comment]
Looks dirty, but trim() is of course better than this dirty regex. 

Thanks :-)
