### ISSUE TITLE
[Nice to have] set values to the checkbox / select item

### ISSUE THREAD

**Issue by lenamtl** [DataTables/Select#39]
I'm using PHP and I'm having a value for each row/line let say $item_id 
so what I wish to able to do is the set my select checkbox to have a that value so I would be able to send the selected values to Ajax.

But it's look like there is no way to assign value to the selections / checkbox 

See my question about this 
https://datatables.net/forums/discussion/comment/162530

**Comment by AllanJard** [comment]
I've [added real checkboxes](https://github.com/DataTables/Select/commit/b50d02725574578a11a36281f98eeedf6343f4af) in Select v2 (which requires DataTables v2, which is in development while I'm updating the extensions). You can set the name and value properties of the checkboxes with the helper function that has been introduced (to be honest, the is secondary to the keyboard accessibility that this introduces).
