### ISSUE TITLE
API method select.info() doesn't return boolean

### ISSUE THREAD

**Issue by mpryvkin** [DataTables/Select#41]
API method `select.info()` doesn't return state of the `info` option when called as `table.select.info()`.

https://github.com/DataTables/Select/blob/295d1be53cd1a8adc7e8f65803ed6942874e6eb1/js/dataTables.select.js#L841-L849

Seems like a typo and the code should be:
```
if ( flag === undefined ) {
```
instead of 
```
if ( info === undefined ) {
```

**Comment by DataTables** [comment]
Thanks for pointing that out to me! Fixed and tested now.
