### ISSUE TITLE
Distribution does not contain types.d.ts

### ISSUE THREAD

**Issue by DreierF** [DataTables/Select#45]
Hi,

The `types.d.ts` file is currently not part of the distribution on npm/unpgk etc. even though the `package.json` references it.
It most likely needs to be included in the `files` section of the `package.json`.

See https://unpkg.com/browse/datatables.net-select@1.3.3/package.json and https://unpkg.com/browse/datatables.net-select@1.3.3/

**Comment by AllanJard** [comment]
You are absolutely right - we've actually [got it in the master branch](https://github.com/DataTables/Dist-DataTables-Select/blob/master/package.json#L9) already, but didn't get it done in time for 1.3.3. We need to do a release of Select which I'll get done soon.

**Comment by yaakovfeldman** [comment]
The release `package.json` contains the line:

    "type": "types.d.ts",

I don't use typescript but shouldn't the field be named `types` not `type`?

When I build my javascript project with esbuild it tells me:

```
▲ [WARNING] "types.d.ts" is not a valid value for the "type" field

    node_modules/datatables.net-select/package.json:9:12:
      9 │     "type": "types.d.ts",
        ╵             ~~~~~~~~~~~~

  The "type" field must be set to either "commonjs" or "module".
```

**Comment by AllanJard** [comment]
The [release repo uses `types`](https://github.com/DataTables/Dist-DataTables-Select/blob/master/package.json#L5). It might be that I need to do a new Select release to get that out.

**Comment by AllanJard** [comment]
The distribution repos and packages all include the type files now (as of sometime last year). Closing as stale.
