### ISSUE TITLE
Checkbox inputs are not properly updated on select operation after new data was added

### ISSUE THREAD

**Issue by jbtronics** [DataTables/Select#51]
Hey, the checkbox inputs of the selects are not properly updated during an API select() or deselect() operation, after some rows was dynamically added or data were loaded via ajax.

The problem seems to be caused here: https://github.com/DataTables/Select/blob/011323858ae180d446da26932ad170a1c5e0cd2a/js/dataTables.select.js#L1056

The methods check if the input should be updated, based on the sType of the column. However, when the underlying data is changed (e.g. adding rows), then the sType value is invalidated internally (set to null). That means that the check fails and the checkbox input element is not updated.

Even if you force an update of the sType value (by calling columns().types() API after table initialization) the invalidation of the _aSortData  in the next lines fail, because the array is not existing.

**Comment by jlopes90** [comment]
When will v2.0.1 be released? Because I also have this problem due to the "_aSortData" error.

**Comment by AllanJard** [comment]
Aiming for later today or tomorrow. Apologies for the delay!
