### ISSUE TITLE
Feature request - Add possibility to select all items on current page instead of full table

### ISSUE THREAD

**Issue by lvmajor** [DataTables/Select#54]
https://github.com/DataTables/Select/blob/3ea895837cd5823f97f495b7877657d02d03088d/js/dataTables.select.js#L1346

I don't know if this was already considered or not, but I know this is a possibility in the wonderful but older extension made by @mpryvkin (https://github.com/gyrocode/jquery-datatables-checkboxes) and I wondered if it could be possible to also add it in the native extension? 

I will try to provide a PR this week if I can free up some time for it :) 

For reference, here's how it was implemented in the other extension: https://github.com/gyrocode/jquery-datatables-checkboxes/blob/af373b4b645417984012515d6a4d967f5f61b4f4/js/dataTables.checkboxes.js#L599

**Comment by AllanJard** [comment]
What's the UI for this in the gyrocode project? I didn't see a demo specifically of that, but I might have just missed it.

For DataTables, you just need to do `table.rows({page: 'current'}).select();`. You could call that from a button or anything else you want.

**Comment by dagframstad** [comment]
No demo I think, but it is documented [here](https://www.gyrocode.com/projects/jquery-datatables-checkboxes/reference/options/#columns.checkboxes.selectAllPages)

A nice feature I think. I use this plugin in my applications to execute stuff on the server side, like starting a service etc. I wouldn't want a service that I couldn't see on the current page to execute when checking the header checkbox and clicking a button.

I think this is the only feature missing from datatables-select to allow me to replace the gyrocode plugin (which has been working flawlessly btw).

**Comment by AllanJard** [comment]
So if we take [this example](https://datatables.net/extensions/select/examples/checkbox/checkbox.html) you want an option so that the header checkbox would select only the visible rows - is that correct?

I'm not adverse to that at all. The `select.headerCheckbox` option could be extended from just a boolean to allow a string as well `none`, `select-all`, `select-page` for example, where `none === false` and `select-all === true`.

Anyone fancy sending a pull request? :)

**Comment by dagframstad** [comment]
I gave it a shot. I'm just an amateur with javascript, I do mostly backend coding with Kotlin and Java, so please feel free to modify as you please.

**Comment by dagframstad** [comment]
The code I use in my projects use the gyrocode checkboxes with selectAllPages set to false and I deselect all checkboxes in `drawCallback`, to avoid confusion with having pages with selected checkboxes that you can't see after paging.

**Comment by AllanJard** [comment]
Merged in and will be in the next release of Select - excellent stuff, that you :-)

**Comment by dagframstad** [comment]
My pleasure. I really appreciate all the great work you've put into datatables. It is really powerful, I've been using it in my customers internal administrative pages for more than 10 years now.
