### ISSUE TITLE
Generating compiled css for releeases

### ISSUE THREAD

**Issue by charlouze** [DataTables/Select#7]
Hey !

I'm using bower to manage my dependencies but my project doesn't have a sass compiler included.

It would be great if releases could include a compiled version of those sass files. Currently, I have to commit the compiled version to my repository. IMHO, it's kind of a bad practise.

**Comment by DataTables** [comment]
It's coming! Updates releases and announcement planned next week. I'll post back here when done.

**Comment by DataTables** [comment]
`datatables.net-select` is the Bower package with the core software. There are styling packages such as `datatables.net-select-dt` which contain the compiled CSS. See [this blog post](http://datatables.net/blog/2015-11-09) for details.

**Comment by charlouze** [comment]
Greate news. Thanks !
