### ISSUE TITLE
TypeError when loading Select extension

### ISSUE THREAD

**Issue by rgriffith** [DataTables/Select#8]
When attempting to load the Select extension (v1.0.1 and v1.1.0-dev) using require, I am getting the following JavaScript error:

```
Uncaught TypeError: Cannot read property 'row' of undefined    dataTables.select.js:565
(anonymous function) @ dataTables.select.js:565
m.extend.each @ jquery-1.11.1.min.js:2
factory @ dataTables.select.js:561
i.execCb @ require-2.1.15.min.js:29
Z.check @ require-2.1.15.min.js:18
Z.enable @ require-2.1.15.min.js:23
Z.init @ require-2.1.15.min.js:17
E @ require-2.1.15.min.js:14
i.completeLoad @ require-2.1.15.min.js:28
i.onScriptLoad @ require-2.1.15.min.js:29
```

I confirmed Data Tables is being loaded first.

Any help would be greatly appreciated.

**Comment by DataTables** [comment]
Can you give me a link to the page showing the issue please?

**Comment by rgriffith** [comment]
Sure, [here is a page](http://072770b4.ngrok.io/) demonstrating a simplified variation of my setup. Let me know if you need anything else from my end. Thanks!

**Comment by DataTables** [comment]
Thanks for the link. It looks like you need to update your DataTables. You are using 1.10.3 - while 1.10.7 or newer (1.10.9 is the current release) is required for Select. It should really have a check - I'll add that.

**Comment by rgriffith** [comment]
Quick update here, I upgraded Data Tables from 1.10.3 to 1.10.9 and the error seemed to go away. I didn't see any version dependencies listed, but perhaps there are?

**Comment by rgriffith** [comment]
Beat me to it, sorry! Was there something in the docu that mentions the version requirements?

**Comment by DataTables** [comment]
No - the software itself should check for the required version. That it is missing that is a bug.

**Comment by rgriffith** [comment]
Ah, ok. I'll go ahead and close this out since the upgrade fixed my issue. Thanks again for all the help!
