### ISSUE TITLE
TypeError: g.ext.selector is undefined during load

### ISSUE THREAD

**Issue by mcagl** [DataTables/Select#9]
Hello, I'm using DataTables 1.10.6 in a project, and I downloaded the Select plugin's js and css from the CDN (which is, as of now, the same as version 1.1.0)

I loaded the js and css after the datatables ones, and during page load I obtain this error in the javascript console (Firefox):

TypeError: g.ext.selector is undefined

line 11, col 504

**Comment by DataTables** [comment]
Select requires DataTables 1.10.7 or newer. The current release is 1.10.10. If you update the issue should be resolved.

**Comment by mcagl** [comment]
Yes, I confirm that with the last DataTables release (1.10.10) the Select plugin works.

Thanks for the quick reply.
